### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by laurisvan** [nodeschool/helsinki#2]
Like  our events, Node School should be inclusive and harassment free, and a stated code of conduct would help.

We can probably use an existing code of conduct, such as https://github.com/nodeschool/berlin/blob/master/codeofconduct.md

**Comment by nikcorg** [comment]
:+1: for reusing the Berlin chapter's CoC.

**Comment by finnp** [comment]
There is also https://github.com/nodeschool/organizers/blob/master/codeofconduct-template.md

**Comment by laurisvan** [comment]
I think the vanilla NodeSchool template is good one; There's a PR https://github.com/nodeschool/helsinki/pull/5 for that - somehow it didn't get injected into this thread regardless of annotating the PR with issue number.

Let's close with that and change to another CoC if needed.
