### ISSUE TITLE
Helsinki chapter logo

### ISSUE THREAD

**Issue by laurisvan** [nodeschool/helsinki#3]
Most of the GitHub pages have a logo - one with HelNode brand would look great.

See the "format" here: https://github.com/nodeschool/nodeschool.github.io/tree/master/images/make-a-sticker

**Comment by d2s** [comment]
Does HelNode have some existing graphics & materials somewhere?

Might be able to help with this.

**Comment by jubilem** [comment]
Hello, here is a link to zip that has logos in PNG and original ai file. I think this is all we have right now:

https://www.dropbox.com/s/pv2ca3b8nhi8eox/Helnode_Logo_CORRECT.zip?dl=0

**Comment by d2s** [comment]
- Downloaded bitmap & vector image assets.
- Created folder structure for the project.
- Color picking two main colors from the HelNode logo.
- Changed background color to orange.
- Changed foreground line color to dark blue.
- Changed 3 letters in the bottom to letters `HEL`.
- Saved preview copy of the edited file to PNG format.
- Saved the edited file to AI format.

Not 100% sure if letters totally align to the guidelines, but did my best to match the example layout structure.

AI version of the file available, if this fits the needs of the event (or if someone smarter wants to do some additional adjustments).

![nodeschool-sticker-helnode--edit](https://cloud.githubusercontent.com/assets/135053/6836976/f5cd18f2-d34f-11e4-898b-797fef4f88ff.png)

**Comment by d2s** [comment]
Just the edited sticker version, exported as a PNG bitmap image.

![nodeschool-sticker-helnode--edit-only](https://cloud.githubusercontent.com/assets/135053/6837102/4aef7202-d351-11e4-9c22-cdb1f4be91df.png)

All of the files (in AI & PNG format) available from:
http://autiomaa.org/2015/nodeschool-helsinki-sticker.zip

**Comment by d2s** [comment]
If you want some alternative versions, just ask. :smile:

**Comment by laurisvan** [comment]
Thanks Daniel! I took the liberty of adding that to our home page already (made a quick edit from the Berlin pages).

I think the logo works now already, but if you get the inspiration to adding some iconic Helsinki landmark there, feel free to send a modified version in this PR.

I think we are good to go, I'm closing this PR.

**Comment by finnp** [comment]
@d2s Awesome! I would love to see this with the Tuomiokirkko as the building. And maybe blue/white Helsinki colors as well?

**Comment by d2s** [comment]
@finnp Have to think of those, if I have some extra time during weekend. :sleeping:

**Comment by finnp** [comment]
@d2s Sure. Try to be inspired by this video https://www.youtube.com/watch?v=y6120QOlsfU :wink:
